version: '{build}'
clone_depth: 1

image:
  - Ubuntu
  - Visual Studio 2017

platform:
  - x86
  - x64

matrix:
  exclude:
    - image: Ubuntu
      platform: x86

branches:
  only:
  - native-CI
  - /^v.*$/

before_build:
  - ps: "Get-ChildItem Env:"

build_script:
  - ps: ./build/build.ps1
   
artifacts:
  - path: "*.zip"

deploy:
  - provider: GitHub
    force_update: true
    auth_token:
      secure: DgOFw4fxC/ZRHeKG+iMYmTCIhHbtCO65+MUqsDwBuBNrfYMub9LNo+Zaj1sB54tN
    artifact: /.*\.zip/
    on:
      APPVEYOR_REPO_TAG: true