version: '{build}'
clone_depth: 1

image:
- Ubuntu
- Visual Studio 2017

branches:
  only:
  - master
  - dev
  - native-CI

before_build:
- ps: "Get-ChildItem Env:"

build_script:
- ps: |
    # define parameters
    $version1 = "1.10.5"
    $version2 = "1_10_5"
    $archiveName = "CMake-hdf5-$version1.zip"
    $topFolderName = "CMake-hdf5-$version1"
    $sourceFolderName = "hdf5-$version1"
    $url = "https://s3.amazonaws.com/hdf-wordpress-1/wp-content/uploads/manual/HDF5/HDF5_$version2/source/CMake-hdf5-$version1.zip"

    # download release
    Invoke-WebRequest -Uri $url -OutFile $archiveName
    Expand-Archive -Path $archiveName -DestinationPath .

    # create build folder
    New-Item -Path ./$topFolderName/build -ItemType directory
    Set-Location -Path ./$topFolderName/build

    # define CMAKE options
    $params = @"
    -DCMAKE_BUILD_TYPE:STRING=Release
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DBUILD_TESTING:BOOL=OFF

    -DHDF5_BUILD_CPP_LIB:BOOL=OFF
    -DHDF5_BUILD_EXAMPLES:BOOL=OFF
    -DHDF5_BUILD_FORTRAN:BOOL=OFF
    -DHDF5_BUILD_HL_LIB:BOOL=OFF
    -DHDF5_BUILD_JAVA:BOOL=OFF
    -DHDF5_BUILD_TOOLS:BOOL=OFF
    -DHDF5_ENABLE_THREADSAFE:BOOL=ON

    -DHDF5_ALLOW_EXTERNAL_SUPPORT:STRING=TGZ
    -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON
    -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON
    -DHDF5_ENABLE_SZIP_ENCODING:BOOL=ON
    -DZLIB_TGZ_NAME:STRING=ZLib.tar.gz
    -DSZIP_TGZ_NAME:STRING=SZip.tar.gz
    -DTGZPATH:PATH=$((Get-Location).Path/..)
    "@.replace("`n"," ")

    # create build files
    if ($isLinux)
    { 
      Invoke-Expression "cmake -G 'Unix Makefiles' $params ./../$sourceFolderName"
    }
    elseif ($isWindows)
    {
      Invoke-Expression "cmake -G 'Visual Studio 15 2017 Win64' $params ./../$sourceFolderName"
    }

    # build
    cmake --build . --config Release

    # collect artifacts
    if ($isLinux)
    {
      Set-Location -Path ./bin
      7z a -tzip ./../../../artifacts.zip ./*hdf5*.so*
    }
    elseif ($isWindows)
    {
      Set-Location -Path ./bin/release
      7z a -tzip ./../../../../artifacts.zip ./*hdf5*.dll
    }

artifacts:
  - path: "artifacts.zip"