git:
  depth: 1

matrix:
  include:
    - os: osx
      osx_image: xcode10.2

branches:
  only:
  - native-CI
  - /^v.*$/

before_install:
  - brew cask install powershell

before_script:
  - pwsh -command "Get-ChildItem Env:"

script:
  - pwsh -command "./build/build.ps1"

deploy:
  provider: releases
  api_key:
    secure: SdDiAS34m3soGRY7aP7Fipwre3swmKxt2qylGiAvgzDgtSRN4cOA280mwpr65IHYBTaIjuiUlOc6KBM7G+EG7pe8UNasjxblmsj2vEQzz/XOfzuZBvTeWNJYJYSmutlqGSn5oZxT5kwlBxKs4f92KcRWB9iEQlUzz5ZOqFOVGbaoCPoLLKRV/benBrwrwwj+5w0I4z5luTfD1ax3rOhK033sGAmz5SZBEg7W5cOdBnGNLStTNc1dJKtCWEg0L3nWnSqdYdZYcESKx4gdSrjfdS9U4y6RS+eFVq3xjqFzJpsk51QbOuAUanQ8RdIuY6BCbcnXIVN2sCKvDFGEDyEoLl34xJrax0MywUc5WlInxl+t5QZEse5NIQYkXjcBzRoAgVqcJmIDcM/01/3EQTIP9yS5MrLJ8AGzqYo77xz02zQbw05DG5DLlS2OMSrDs0nxvnNbcUYWwDN3ZHzQqq5UVjQccr5yg0vShVTLGvqTJIm0em6avo+MmSURBiawI+vgUQP1IJ76FZJEiFLezqOqpvOyUbUPzt6kvZ9xSDDr/scUrcj8HZPesS8ZeBSPJw35t9CLkbJe4+6sIoqQ3B+2Q3MvhdsYJio+83XyRb3S6PaaFMXsIWsZZNQ/xdfBGvfA4A9F2jhBn3KHxIYdIdG1UetaZL01jxTOjuYhGwgjEoM=
  file_glob: true
  file: "*.zip"
  overwrite: true
  skip_cleanup: true
  on:
    tags: true