git:
  depth: 1

matrix:
  include:
    - os: osx
      osx_image: xcode10.2

branches:
  only:
  - native-CI
  - /^v.*$/

before_install:
  - brew cask install powershell

before_script:
  - pwsh -command "Get-ChildItem Env:"

script:
  - pwsh -command "./build/build.ps1"

deploy:
  provider: releases
  api_key:
    secure: swpNcG8yEzfS9sXyaOT+ZJYAuMTV3Yw61UlJfcecJZ4DQxwbS7xINj5/0uajqeT5r7NmnlZHvU7PABqK1C2CvkC8IgnmqjdPuhZb6ODOm9p2ZCHlTOBzzd7p9Zqi8kLjovVZhfdfeHm3FWm+hkm+AWDSkT4akNRyQyGFKzfChDJZ4DAhY6ISOVn+u69e+ubmWYT9o96QAY4iClGfxDbgw4wsyQzzWTEPfBl0lKySD3aojmyyhyj/48PXGmIqF1fYZOR5oJJATztjYCCKeeruo0K518md0X2It8l+qrVQSbBCQRcw38p22tX7GOa3RjOro1Bx4E16nz9OBiBjgp8OHobA6XlB4AVbYba4RXL398mj+9a1J0eezbF4+1goGVqly8fNx5sdZ6dAutsFqrFwv2tyIoJ92Jk5O0nRmmIShO+jiMSGCcJtfE3DH2rqcSDC11PYi1HLC2RQND5wK42cdRb61xzZ4qX4d3GwJw7yM3Rg+/FUYC9iB4KmiYAfAEknbt9/YUH+lt+yCkLtVlnFjvm4vrEiZTD/o2oowymw3uTN5aPalhTm/d+V0uYq8ZaFwI4nzi89m3Vg2dwjOgWOVR4r1OBBBufT9ey05NvJHta6WrYksC4Pld6jt1M5XUPIs3ESNLREWbKdiITiya5nPZc/kdhmSII9HW0TgHIrH74=
  file_glob: true
  file: "*.zip"
  overwrite: true
  skip_cleanup: true
  on:
    tags: true